image: maven

stages:
  - 构建

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache"

cache:
  paths:
    - .m2/repository/
    - target/

Packaging:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - targets/*.jar
