image: docker-registry.uuzdream.cn/ci-env/maven:3.6.3-jdk-8

stages:
  - 构建

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    - mv ./Core/target/YuyukoBotCore.jar ./
    - mv ./LaunchWrapper/target/YuyukoBot-LaunchWrapper.jar ./
    - zip -r9 ./YuyukoBot.zip ./YuyukoBotCore.jar ./YuyukoBot-LaunchWrapper.jar ./*.cmd ./*.sh ./MCProtocolLib
  artifacts:
    paths:
      - $CI_PROJECT_DIR/YuyukoBot.zip
