image: maven

stages:
  - 准备构建
  - 构建
  - 存档

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

Preparing:
  stage: 准备构建
  script:
    - mvn $MAVEN_CLI_OPTS clean
    - mvn $MAVEN_CLI_OPTS clean package

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS compile

Packaging:
  stage: 存档
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - targets/*.jar
