image: maven:3.6.3-jdk-8

stages:
  - 构建

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    - zip -r ./YuyukoBot.zip ./Core/target/YuyukoBotCore.jar ./LaunchWapper/target/YuyukoBotCore.jar ./*.cmd ./*.sh ./MCProtocolLib
  artifacts:
    paths:
      - $CI_PROJECT_DIR/YuyukoBot.zip
