image: docker-registry.uuzdream.cn/ci-env/maven:3.6.3-jdk-8

stages:
  - 构建

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    - cp -r ./MCProtocolLib ./artifacts
    - cp ./*.cmd ./artifacts
    - cp ./*.sh ./artifacts
    - cd artifacts
    - zip -r9 ./YuyukoBot.zip ./
  artifacts:
    paths:
      - $CI_PROJECT_DIR/YuyukoBot.zip
