image: maven

stages:
  - 构建

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - $CI_PROJECT_DIR/target/*.jar
