image: maven

stages:
  - 构建

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache"

cache:
  paths:
    - /cache

Build:
  stage: 构建
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - $CI_PROJECT_DIR/targets/**.jar
