image: maven

stages:
  - 准备构建
  - 构建
  - 存档

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

Preparing:
  stage: 准备构建
  script:
    - mvn clean
    - mvn clean package

Build:
  stage: 构建
  script:
    - mvn compile

Packaging:
  stage: 存档
  script:
    - mvn package
  artifacts:
    paths:
      - targets/*.jar
